In [2]:
import torch

In [3]:
a = torch.FloatTensor([1.])
a.require_grad = True

In [5]:
a * 8

tensor([8.])

In [13]:
from torch.distributions.categorical import Categorical

a = torch.randn(64, 89)
Categorical(logits=a).sample()

tensor([73, 44, 43,  2, 59, 64, 31, 44, 63, 54, 39, 13, 75, 85, 22, 75, 14, 11,
        32, 31, 42, 69, 26, 67,  3,  8, 62, 52, 53, 28, 65, 41,  0, 34, 74, 42,
         5, 22, 73,  6, 14, 28, 36,  3, 48, 19, 76, 58, 24, 35, 46, 86, 61, 85,
         7, 49,  7, 54, 53, 59, 65, 88, 20, 12])

In [12]:
a.a

tensor([[ 0.1054, -1.2316,  0.4835,  ...,  0.4286,  0.7701,  1.0745],
        [ 0.6023,  1.3250, -0.7631,  ..., -0.7145, -1.0927,  2.1734],
        [-0.6037, -0.7208,  0.8215,  ...,  1.9170,  0.9989, -0.4453],
        ...,
        [-0.6038,  0.1183,  0.5333,  ...,  1.5139, -0.0906,  0.6977],
        [ 0.1483,  0.4950,  0.6965,  ...,  0.7408,  0.5077, -0.3870],
        [-0.1407, -0.6000,  1.4597,  ...,  0.1278, -0.5380, -0.8911]])